[package]
name = "bd-ical-creator"
authors = ["kontakt@der-fetzer.de"]
version = "0.1.0"
edition = "2021"

[dependencies]
ics = "0.5.8"
clap = "4.1.11"
chrono = "0.4.24"
uuid = { version = "1.3.0", features = ["v4"] }
